/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/chainsawmangrave.glb 
*/

import React from 'react'
import { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/assets/chainsawmangrave.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  // const { actions } = useAnimations(animations, group)
   const { actions, names } = useAnimations(animations, group)

  // Add this useEffect to play the animation on a loop
  useEffect(() => {
    // 'names' is an array of all animation names in your file
    console.log('Available animations:', names)

    // Play the first animation
    if (names.length) {
      actions[names[0]].play()
    }
  }, [actions, names])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <group name="clothes000">
            <skinnedMesh name="平面008" geometry={nodes.平面008.geometry} material={materials['MAT_ChainSawMan_Clothes.000']} skeleton={nodes.平面008.skeleton} />
            <skinnedMesh name="平面008_1" geometry={nodes.平面008_1.geometry} material={materials['MAT_ChainSawMan_clothes_line.000']} skeleton={nodes.平面008_1.skeleton} />
          </group>
          <group name="clothes001">
            <skinnedMesh name="平面010" geometry={nodes.平面010.geometry} material={materials['MAT_ChainSawMan_Clothes.001']} skeleton={nodes.平面010.skeleton} />
            <skinnedMesh name="平面010_1" geometry={nodes.平面010_1.geometry} material={materials['MAT_ChainSawMan_clothes_line.001']} skeleton={nodes.平面010_1.skeleton} />
          </group>
          <group name="arm">
            <skinnedMesh name="平面013" geometry={nodes.平面013.geometry} material={materials.MAT_ChainSawMan_Arm} skeleton={nodes.平面013.skeleton} />
            <skinnedMesh name="平面013_1" geometry={nodes.平面013_1.geometry} material={materials.MAT_ChainSawMan_arm_line} skeleton={nodes.平面013_1.skeleton} />
          </group>
          <group name="Box000">
            <skinnedMesh name="平面009" geometry={nodes.平面009.geometry} material={materials['MAT_ChainSawMan_Head_Box.000']} skeleton={nodes.平面009.skeleton} />
            <skinnedMesh name="平面009_1" geometry={nodes.平面009_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.平面009_1.skeleton} />
          </group>
          <group name="Box001">
            <skinnedMesh name="平面024" geometry={nodes.平面024.geometry} material={materials['MAT_ChainSawMan_Head_Box.001']} skeleton={nodes.平面024.skeleton} />
            <skinnedMesh name="平面024_1" geometry={nodes.平面024_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.平面024_1.skeleton} />
          </group>
          <group name="Box002">
            <skinnedMesh name="平面026" geometry={nodes.平面026.geometry} material={materials['MAT_ChainSawMan_Head_Box.002']} skeleton={nodes.平面026.skeleton} />
            <skinnedMesh name="平面026_1" geometry={nodes.平面026_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.平面026_1.skeleton} />
          </group>
          <group name="Handle000">
            <skinnedMesh name="圆环007" geometry={nodes.圆环007.geometry} material={materials['MAT_ChainSawMan_Handle.000']} skeleton={nodes.圆环007.skeleton} />
            <skinnedMesh name="圆环007_1" geometry={nodes.圆环007_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环007_1.skeleton} />
          </group>
          <group name="Handler001">
            <skinnedMesh name="平面" geometry={nodes.平面.geometry} material={materials['MAT_ChainSawMan_Head_Handler.001']} skeleton={nodes.平面.skeleton} />
            <skinnedMesh name="平面_1" geometry={nodes.平面_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.平面_1.skeleton} />
          </group>
          <group name="HeadMain">
            <skinnedMesh name="圆环004" geometry={nodes.圆环004.geometry} material={materials.MAT_ChainSawMan_Head_Main} skeleton={nodes.圆环004.skeleton} />
            <skinnedMesh name="圆环004_1" geometry={nodes.圆环004_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环004_1.skeleton} />
          </group>
          <group name="JawB">
            <skinnedMesh name="平面006" geometry={nodes.平面006.geometry} material={materials['MAT_ChainSawMan_Head_Jaw.B']} skeleton={nodes.平面006.skeleton} />
            <skinnedMesh name="平面006_1" geometry={nodes.平面006_1.geometry} material={materials.MAT_ChainSawMan_Jaw_Line} skeleton={nodes.平面006_1.skeleton} />
          </group>
          <group name="JawT">
            <skinnedMesh name="平面005" geometry={nodes.平面005.geometry} material={materials['MAT_ChainSawMan_Head_Jaw.T']} skeleton={nodes.平面005.skeleton} />
            <skinnedMesh name="平面005_1" geometry={nodes.平面005_1.geometry} material={materials.MAT_ChainSawMan_Jaw_Line} skeleton={nodes.平面005_1.skeleton} />
          </group>
          <group name="Jaw_Chain000">
            <skinnedMesh name="圆环005" geometry={nodes.圆环005.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环005.skeleton} />
            <skinnedMesh name="圆环005_1" geometry={nodes.圆环005_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环005_1.skeleton} />
          </group>
          <group name="Jaw_Chain001">
            <skinnedMesh name="圆环010" geometry={nodes.圆环010.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环010.skeleton} />
            <skinnedMesh name="圆环010_1" geometry={nodes.圆环010_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环010_1.skeleton} />
          </group>
          <skinnedMesh name="leg" geometry={nodes.leg.geometry} material={materials.MAT_ChainSawMan_leg} skeleton={nodes.leg.skeleton} />
          <skinnedMesh name="Neck_Chain000" geometry={nodes.Neck_Chain000.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.Neck_Chain000.skeleton} />
          <group name="Neck_Chain001">
            <skinnedMesh name="圆环018" geometry={nodes.圆环018.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环018.skeleton} />
            <skinnedMesh name="圆环018_1" geometry={nodes.圆环018_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环018_1.skeleton} />
          </group>
          <group name="Neck_Chain002">
            <skinnedMesh name="圆环012" geometry={nodes.圆环012.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环012.skeleton} />
            <skinnedMesh name="圆环012_1" geometry={nodes.圆环012_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环012_1.skeleton} />
          </group>
          <group name="Neck_Chain003">
            <skinnedMesh name="圆环011" geometry={nodes.圆环011.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环011.skeleton} />
            <skinnedMesh name="圆环011_1" geometry={nodes.圆环011_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环011_1.skeleton} />
          </group>
          <group name="Neck_Chain004">
            <skinnedMesh name="圆环015" geometry={nodes.圆环015.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环015.skeleton} />
            <skinnedMesh name="圆环015_1" geometry={nodes.圆环015_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环015_1.skeleton} />
          </group>
          <group name="Neck_Chain005">
            <skinnedMesh name="圆环016" geometry={nodes.圆环016.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环016.skeleton} />
            <skinnedMesh name="圆环016_1" geometry={nodes.圆环016_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环016_1.skeleton} />
          </group>
          <group name="Neck_Chain006">
            <skinnedMesh name="圆环017" geometry={nodes.圆环017.geometry} material={materials.MAT_ChainSawMan_Chain} skeleton={nodes.圆环017.skeleton} />
            <skinnedMesh name="圆环017_1" geometry={nodes.圆环017_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环017_1.skeleton} />
          </group>
          <skinnedMesh name="necktie001" geometry={nodes.necktie001.geometry} material={materials['MAT_ChainSawMan_Necktie.001']} skeleton={nodes.necktie001.skeleton} />
          <skinnedMesh name="necktie002" geometry={nodes.necktie002.geometry} material={materials['MAT_ChainSawMan_Necktie.002']} skeleton={nodes.necktie002.skeleton} />
          <group name="Roller000">
            <skinnedMesh name="圆环002" geometry={nodes.圆环002.geometry} material={materials['MAT_ChainSawMan_Roller.000']} skeleton={nodes.圆环002.skeleton} />
            <skinnedMesh name="圆环002_1" geometry={nodes.圆环002_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环002_1.skeleton} />
          </group>
          <group name="Roller001">
            <skinnedMesh name="圆环003" geometry={nodes.圆环003.geometry} material={materials['MAT_ChainSawMan_Roller.001']} skeleton={nodes.圆环003.skeleton} />
            <skinnedMesh name="圆环003_1" geometry={nodes.圆环003_1.geometry} material={materials.MAT_ChainSawMan_Head_line} skeleton={nodes.圆环003_1.skeleton} />
          </group>
          <group name="shoes">
            <skinnedMesh name="平面012" geometry={nodes.平面012.geometry} material={materials.MAT_ChainSawMan_Shoes} skeleton={nodes.平面012.skeleton} />
            <skinnedMesh name="平面012_1" geometry={nodes.平面012_1.geometry} material={materials.MAT_ChainSawMan_shoes_line} skeleton={nodes.平面012_1.skeleton} />
          </group>
          <group name="TeethB">
            <skinnedMesh name="NURBS_路径003" geometry={nodes.NURBS_路径003.geometry} material={materials['MAT_ChainSawMan_Head_Teeth.B']} skeleton={nodes.NURBS_路径003.skeleton} />
            <skinnedMesh name="NURBS_路径003_1" geometry={nodes.NURBS_路径003_1.geometry} material={materials.MAT_ChainSawMan_Teeth_line} skeleton={nodes.NURBS_路径003_1.skeleton} />
          </group>
          <group name="TeethT">
            <skinnedMesh name="NURBS_路径001" geometry={nodes.NURBS_路径001.geometry} material={materials['MAT_ChainSawMan_Head_Teeth.T']} skeleton={nodes.NURBS_路径001.skeleton} />
            <skinnedMesh name="NURBS_路径001_1" geometry={nodes.NURBS_路径001_1.geometry} material={materials.MAT_ChainSawMan_Teeth_line} skeleton={nodes.NURBS_路径001_1.skeleton} />
          </group>
          <skinnedMesh name="window000" geometry={nodes.window000.geometry} material={materials['MAT_ChainSawMan_Head_Window.000']} skeleton={nodes.window000.skeleton} />
          <skinnedMesh name="window001" geometry={nodes.window001.geometry} material={materials['MAT_ChainSawMan_Head_Window.001']} skeleton={nodes.window001.skeleton} />
        </group>
        <group name="Center" />
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cube">
              <mesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials.Material} position={[-1.972, 4.535, -1.227]} rotation={[0.051, -0.004, 0.158]} scale={[7.713, 5.979, 5.979]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/chainsawmangrave.glb')
